import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译文本
const translations = {
  en: {
    // Navigation
    'nav.mtfAgent': 'MTF Agent',
    'nav.dashboard': 'Predicted Trends',
    'nav.watchlist': 'Watchlist',
    'nav.portfolio': 'Portfolio',
    'nav.news': 'Finance News',
    'nav.pricing': 'VIP Membership',
    'nav.admin': 'Admin',
    'nav.settings': 'Settings',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.comingSoon': 'Coming Soon',
    'common.comingSoonDesc': 'This feature is currently under development.',
    'common.settings': 'Settings',
    'common.logout': 'Logout',
    'common.on': 'ON',
    'common.off': 'OFF',
    'common.open': 'Open',
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.clear': 'Clear',
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage language preference and account access.',
    'settings.close': 'Close settings',
    'settings.languageTitle': 'Language',
    'settings.languageDesc': 'Switch the interface language.',
    'settings.accountTitle': 'Account',
    'settings.accountDesc': 'Sign out of the current account safely.',
    'settings.demoDesc': 'You are in demo mode. Logging out will return to the landing page.',
    'settings.aiModelTitle': 'AI Model Config',
    'settings.aiModelDesc': 'Configure the OpenAI-compatible model used for smart analysis.',
    'settings.aiRecommended': 'Recommended',
    'settings.aiKeyKeepPlaceholder': 'Leave empty to keep the saved key',
    'settings.saveAIConfig': 'Save Config',
    'settings.saving': 'Saving...',
    'settings.aiSaved': 'AI model config saved',
    'settings.aiLoadFailed': 'Failed to load AI model config',
    'settings.aiSaveFailed': 'Failed to save AI model config',
    'settings.modelConfigTab': 'Model Config',
    'settings.accountSettingsTab': 'Account Settings',
    'settings.inviteTitle': 'Membership Invite Code',
    'settings.inviteDesc': 'Enter an invite code from an administrator to activate or extend your membership.',
    'settings.inviteCodeRequired': 'Please enter an invite code',
    'settings.inviteRedeeming': 'Redeeming...',
    'settings.inviteRedeem': 'Redeem Membership',
    'settings.inviteRedeemSuccess': 'Redeemed successfully. Current membership level {level}, valid until {date}',
    'settings.inviteRedeemFailed': 'Failed to redeem invite code',
    
    // Dashboard
    'dashboard.title': 'Predicted Trends',
    'dashboard.subtitle': 'AI-powered forecasts for your favorite stocks.',
    'dashboard.predictions': 'AI Predictions',
    'dashboard.performance': 'Performance',
    'dashboard.addStock': 'Add Watching',
    'dashboard.addToWatchlist': 'Add to Watchlist',
    'dashboard.addedToWatchlist': 'Watched',
    'dashboard.errorTitle': 'An Error Occurred',
    'dashboard.filters.all': 'All',
    'dashboard.filters.highestConfidence': 'Highest Confidence',
    'dashboard.filters.potentialGrowth': 'Potential Growth',
    'dashboard.filters.bullish': 'Bullish',
    'dashboard.filters.bearish': 'Bearish',
    'dashboard.noStocks': 'No stocks found matching your criteria.',
    
    // Add Stock Modal
    'addStock.title': 'Add to Watchlist',
    'addStock.type': 'Type',
    'addStock.typeStock': 'Stock',
    'addStock.typeEtf': 'ETF',
    'addStock.exchange': 'Exchange',
    'addStock.exchangeSh': 'Shanghai (sh)',
    'addStock.exchangeSz': 'Shenzhen (sz)',
    'addStock.stockCode': 'Stock Code',
    'addStock.stockCodeHint': '(6 digits)',
    'addStock.stockCodePlaceholder': 'e.g. 600000',
    'addStock.fullCode': 'Full Code:',
    'addStock.errorLength': 'Please enter 6 digits',
    'addStock.errorNumeric': 'Code must contain only numbers',
    'addStock.errorNotFound': 'Code not found, please use full format e.g. sz000001 or sh600519',
    'addStock.errorAuth': 'Please login first',
    'addStock.errorDuplicate': 'Already in watchlist',
    'addStock.errorLimitExceeded': 'Watchlist limit reached for your current membership.',
    'addStock.errorGeneric': 'Failed to add',

    // Modal Common
    'modal.deleteTitle': 'Remove Stock',
    'modal.deleteMessage': 'Are you sure you want to remove {symbol}?',
    'modal.deleteConfirm': 'Delete',
    'modal.deleteCancel': 'Cancel',
    
    // Watchlist Extra
    'watchlist.latestDate': 'Latest Date',
    'watchlist.turnoverRate': 'Turnover Rate',
    
    // Strategy
    'strategy.badge': 'Strategy',
    'strategy.configure': 'Configure Parameters',
    'strategy.initialCash': 'Initial Cash',
    'strategy.rebalance': 'Rebalance',
    'strategy.threshold': 'Buy/Sell Threshold',
    'strategy.position': 'Position Range',
    'strategy.noConfig': 'No strategy configured',
    'strategy.configureNow': 'Configure Now',

    // Watchlist
    'watchlist.title': 'My Watchlist',
    'watchlist.subtitle': 'Track your favorite stocks and monitor their performance.',
    'watchlist.searchPlaceholder': 'Search...',
    'watchlist.addStock': 'Add Watching',
    'watchlist.ticker': 'Code / Company',
    'watchlist.lastPrice': 'Last Price',
    'watchlist.todayChange': 'Latest Change',
    'watchlist.chart': 'Chart',
    'watchlist.actions': 'Actions',
    'watchlist.showChart': 'Show chart',
    'watchlist.singlePredict': 'Single prediction',
    'watchlist.tabStock': 'Stocks',
    'watchlist.tabEtf': 'ETFs',
    'watchlist.emptyTitle': 'Your watchlist is empty',
    'watchlist.emptySubtitle': 'Use the search bar above to find and add your first stock.',
    'watchlist.noPredictionData': 'No prediction data available.',
    'watchlist.overLimitBadge': 'Paused',
    'watchlist.overLimitHint': 'Over current membership limit. Delete other items or upgrade to enable predictions.',
    // Single Prediction
    'singlePrediction.title': 'MTF Prediction',
    'singlePrediction.submit': 'Run Prediction',
    'singlePrediction.submitting': 'Queued...',
    'singlePrediction.horizonLabel': 'Prediction Period',
    'singlePrediction.contextLabel': 'Prediction Depth',
    'singlePrediction.queueTitle': 'Queue Status',
    'singlePrediction.jobId': 'Job ID',
    'singlePrediction.reused': 'Reused',
    'singlePrediction.queueDepth': 'Queue Depth',
    'singlePrediction.backend': 'Backend',
    'singlePrediction.stockType': 'Stock Type',
    'singlePrediction.latestPrice': 'Latest Price',
    'singlePrediction.mtfVersion': 'MTF Version',
    'singlePrediction.defaultYears': 'History Years',
    'singlePrediction.bestItem': 'Best Quantile',
    'singlePrediction.latestDataDate': 'Latest Data Date',
    'singlePrediction.cutoffDate': 'Cutoff Date',
    'singlePrediction.autoToday': 'Auto today',
    'singlePrediction.cacheHit': 'Cache Hit',
    'singlePrediction.resultTitle': 'Future Price Forecast',
    'singlePrediction.predictedChange': 'Predicted Change',
    'singlePrediction.emptyTitle': 'No direct prediction yet',
    'singlePrediction.emptySubtitle': 'Choose prediction period and depth, then submit one prediction for this symbol.',
    'singlePrediction.statusIdle': 'Idle',
    'singlePrediction.statusQueued': 'Queued',
    'singlePrediction.statusRunning': 'Running',
    'singlePrediction.statusSucceeded': 'Succeeded',
    'singlePrediction.statusFailed': 'Failed',
    'singlePrediction.checking': 'Checking cache...',
    'singlePrediction.checkingTitle': 'Checking existing prediction',
    'singlePrediction.checkingSubtitle': 'The dialog is querying the latest cached single prediction result for this symbol.',
    'singlePrediction.cachedReadonly': 'Existing result loaded',
    'singlePrediction.yes': 'Yes',
    'singlePrediction.no': 'No',
    'singlePrediction.errorGeneric': 'Failed to run prediction',
    'singlePrediction.errorMissingJob': 'Job accepted but job ID is missing.',
    'singlePrediction.errorMissingResult': 'Prediction completed but result payload is missing.',
    'singlePrediction.errorTimeout': 'Prediction timed out while waiting for completion.',
    'singlePrediction.errorMissingBest': 'No historical best model exists for this model and parameter set. Train MTF first.',
    
    // Pricing
    'pricing.title': 'Unlock Premium Features',
    'pricing.subtitle': 'Enhance your investment strategy with powerful tools and real-time insights designed for serious investors.',
    'pricing.features.realTimeData': 'Real-Time Market Data',
    'pricing.features.realTimeDataDesc': 'Stay ahead of the market with instant data updates, no delays.',
    'pricing.features.advancedCharting': 'Advanced Charting Tools',
    'pricing.features.advancedChartingDesc': 'Utilize professional-grade tools for in-depth technical analysis.',
    'pricing.features.aiInsights': 'AI-Powered Insights',
    'pricing.features.aiInsightsDesc': 'Leverage our AI to analyze your portfolio and uncover new opportunities.',
    'pricing.features.unlimitedWatchlists': 'Unlimited Watchlists',
    'pricing.features.unlimitedWatchlistsDesc': 'Track all the stocks you\'re interested in with no limits.',
    'pricing.features.exclusiveCommunity': 'Exclusive Community',
    'pricing.features.exclusiveCommunityDesc': 'Join a private community of expert traders to share strategies.',
    'pricing.features.adFree': 'Ad-Free Experience',
    'pricing.features.adFreeDesc': 'Focus on your investments with a clean, distraction-free interface.',
    'pricing.comparePlans': 'Compare Our Plans',
    'pricing.feature': 'Feature',
    'pricing.free': 'Free',
    'pricing.vip': 'VIP',
    'pricing.dataRefreshRate': 'Data Refresh Rate',
    'pricing.standard': 'Standard',
    'pricing.realTime': 'Real-time',
    'pricing.numberOfWatchlists': 'Number of Watchlists',
    'pricing.unlimited': 'Unlimited',
    'pricing.advancedAnalytics': 'Advanced Analytics',
    'pricing.aiPortfolioInsights': 'AI Portfolio Insights',
    'pricing.exclusiveCommunityAccess': 'Exclusive Community Access',
    'pricing.prioritySupport': 'Priority Customer Support',
    'pricing.adFreeExperience': 'Ad-Free Experience',
    'pricing.vipMembership': 'VIP Membership',
    'pricing.monthlyPrice': '$19',
    'pricing.perMonth': '/ mo',
    'pricing.billingInfo': 'Billed monthly, cancel anytime.',
    'pricing.allVipFeatures': 'All VIP features included',
    'pricing.priorityCustomerSupport': 'Priority customer support',
    'pricing.earlyAccess': 'Early access to beta features',
    'pricing.upgradeToVip': 'Upgrade to VIP',
    
    // Login
    'login.title': 'Your Portfolio, Perfected.',
    'login.subtitle': 'Track your stocks with AI-powered predictions and unparalleled insight. Make smarter investment decisions today.',
    'login.welcomeBack': 'Welcome Back',
    'login.createAccount': 'Create an Account',
    'login.fullName': 'Full Name',
    'login.fullNamePlaceholder': 'Enter your full name',
    'login.emailAddress': 'Email Address',
    'login.emailPlaceholder': 'Enter your email',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.activationCode': 'Activation Code',
    'login.activationCodePlaceholder': 'Optional activation code',
    'login.signIn': 'Login',
    'login.register': 'Register',
    'login.forgotPassword': 'Forgot Password?',
    'login.loginTab': 'Login',
    'login.registerTab': 'Register',
    'login.or': 'OR',
    'login.continueWithGoogle': 'Continue with Google',
    'login.loginButton': 'Login',
    'login.registerButton': 'Register',
    'login.rememberPassword': 'Remember password',
    'login.loggingIn': 'Logging in...',
    'login.registering': 'Registering...',
    'login.captchaReady': 'Security check ready',
    'login.captchaLoading': 'Loading security check...',
    'login.captchaFailed': 'Security check failed. Please try again.',
    'login.captchaLoadFailed': 'Unable to load security check.',
    'login.captchaUnavailable': 'Security check is unavailable.',

    // Auth
    'auth.sessionExpired': 'Session Expired',
    'auth.redirectingLogin': 'Please login first, redirecting...',
    'auth.checking': 'Checking login status...',

    // Admin
    'admin.noAccessTitle': 'No Admin Access',
    'admin.noAccessDesc': 'The current account cannot access the admin page.',

    // UZI / Research Skill
    'watchlist.uziManage': 'Research Reports',
    'uzi.title': 'Research Skill',
    'uzi.subtitle': 'Manage UZI report search, generation, and deletion in one place.',
    'uzi.invalidTicker': 'Please enter a valid ticker, e.g. 601766.SH',
    'uzi.ticker': 'Ticker',
    'uzi.tickerPlaceholder': 'e.g. 601766.SH or sh601766',
    'uzi.generateDepth': 'Generation Depth',
    'uzi.query': 'Query',
    'uzi.refresh': 'Refresh',
    'uzi.generating': 'Generating...',
    'uzi.generate': 'Generate',
    'uzi.reportList': 'Report List',
    'uzi.reportCount': 'reports',
    'uzi.emptyHint': 'No UZI reports have been generated yet',
    'uzi.empty': 'No UZI reports yet. Generate one above.',
    'uzi.updatedAt': 'Updated',
    'uzi.open': 'Open',
    'uzi.deleting': 'Deleting...',
    'uzi.delete': 'Delete',
    'uzi.searchPlaceholder': 'Search ticker or directory',
    
    // Language
    'language.switch': 'Language',
    'language.english': 'English',
    'language.chinese': '中文',

    // Sidebar
    'sidebar.hello': 'Hello',
    'sidebar.loading': 'Loading...',
    'sidebar.title': 'MeetLife AI',
    'sidebar.member.standard': 'Standard Member',

    // MTF Agent
    'mtfAgent.title': 'MTF Agent',
    'mtfAgent.open': 'Open MTF Agent',
    'mtfAgent.close': 'Close MTF Agent',
    'mtfAgent.resize': 'Resize MTF Agent drawer',
    'mtfAgent.dragResize': 'Drag to resize',
    'mtfAgent.memory': 'Long-term Memory',
    'mtfAgent.reset': 'Reset Session',
    'mtfAgent.emptyResponse': 'MTF Agent did not return content. Please try again later.',
    'mtfAgent.configRequired': 'Please configure the AI model in Settings first.',
    'mtfAgent.runtimeUnavailable': 'MTF Agent runtime is not connected.',
    'mtfAgent.unavailable': 'MTF Agent is unavailable',
    'mtfAgent.resetSuccess': 'Reset to a new MTF Agent session.',
    'mtfAgent.resetFailed': 'Failed to reset session',
    'mtfAgent.memoryLoadFailed': 'Failed to load long-term memory',
    'mtfAgent.memoryClearFailed': 'Failed to clear long-term memory',
    'mtfAgent.waitRuntime': 'Waiting for runtime connection',
    'mtfAgent.memoryTitle': 'Long-term Preferences',
    'mtfAgent.loadingMemory': 'Loading...',
    'mtfAgent.emptyMemory': 'No long-term preferences yet',
    'mtfAgent.connecting': 'Connecting to MTF Agent...',
    'mtfAgent.emptyHint': 'Ask about watchlists, predictions, UZI reports, or portfolio questions.',
    'mtfAgent.thinking': 'Thinking...',
    'mtfAgent.resetConfirmText': 'Resetting creates a new long-term session and clears messages in this window.',
    'mtfAgent.resetting': 'Resetting',
    'mtfAgent.confirmReset': 'Confirm Reset',
    'mtfAgent.goSettings': 'Go to Settings',
    'mtfAgent.placeholder': 'Ask about watchlists, predictions, reports, or portfolio...',
    
    // Landing Page
    'landing.startForFree': 'Start for Free',
    'landing.viewDemo': 'View Demo',
    'landing.features.aiPredictions': 'AI Predictions',
    'landing.features.aiPredictionsDesc': 'Advanced machine learning algorithms forecasting stock movements.',
    'landing.features.realTimeAnalysis': 'Real-time Analysis',
    'landing.features.realTimeAnalysisDesc': 'Live market data analysis to keep you ahead of the curve.',
    'landing.features.securePortfolio': 'Secure Portfolio',
    'landing.features.securePortfolioDesc': 'Bank-grade security to protect your investment data.',
    'landing.footer.rights': '© 2024 FinTrack. All rights reserved.',

    // Stock Prediction Card
    'prediction.model': 'Model',
    'prediction.context': 'Depth',
    'prediction.horizon': 'Period',
    'prediction.days': 'days',
    'prediction.maxDev': 'Max Dev.',
    'prediction.score': 'Score',
    'prediction.actual': 'Actual',
    'prediction.pred': 'Pred',
    'prediction.actChg': 'Actual Chg',
    'prediction.predChg': 'Forecast Chg',
    'prediction.watchlistCount': 'Watching',
    'prediction.hideMetrics': 'Hide metrics',
    'prediction.showMetrics': 'Show metrics',
    'prediction.awaitingAI': 'Awaiting AI prediction...',
  },
  zh: {
    // Navigation
    'nav.mtfAgent': 'MTF 智能体',
    'nav.dashboard': '预测趋势',
    'nav.watchlist': '关注列表',
    'nav.portfolio': '投资策略',
    'nav.news': '财经资讯',
    'nav.pricing': 'VIP会员',
    'nav.admin': '管理员',
    'nav.settings': '设置',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.comingSoon': '即将推出',
    'common.comingSoonDesc': '此功能正在开发中。',
    'common.settings': '设置',
    'common.logout': '登出',
    'common.on': '开',
    'common.off': '关',
    'common.open': '打开',
    'common.close': '关闭',
    'common.cancel': '取消',
    'common.clear': '清空',
    'settings.title': '设置',
    'settings.subtitle': '管理语言偏好与登录状态。',
    'settings.close': '关闭设置',
    'settings.languageTitle': '语言',
    'settings.languageDesc': '切换界面显示语言。',
    'settings.accountTitle': '账户',
    'settings.accountDesc': '安全退出当前账号。',
    'settings.demoDesc': '当前为演示模式，退出后将返回首页。',
    'settings.aiModelTitle': 'AI 模型配置',
    'settings.aiModelDesc': '配置用于智能分析的兼容 OpenAI 接口模型。',
    'settings.aiRecommended': '推荐',
    'settings.aiKeyKeepPlaceholder': '留空则继续使用已保存密钥',
    'settings.saveAIConfig': '保存配置',
    'settings.saving': '保存中...',
    'settings.aiSaved': 'AI 模型配置已保存',
    'settings.aiLoadFailed': '加载 AI 模型配置失败',
    'settings.aiSaveFailed': '保存 AI 模型配置失败',
    'settings.modelConfigTab': '模型配置',
    'settings.accountSettingsTab': '账号设置',
    'settings.inviteTitle': '会员邀请码',
    'settings.inviteDesc': '输入管理员发放的邀请码开通或续期会员。',
    'settings.inviteCodeRequired': '请输入邀请码',
    'settings.inviteRedeeming': '兑换中...',
    'settings.inviteRedeem': '兑换会员',
    'settings.inviteRedeemSuccess': '兑换成功，当前会员等级 {level}，有效期至 {date}',
    'settings.inviteRedeemFailed': '邀请码兑换失败',
    
    // Dashboard
    'dashboard.title': '预测趋势',
    'dashboard.subtitle': '为您喜爱的股票提供AI驱动的预测。',
    'dashboard.predictions': 'AI预测',
    'dashboard.performance': '表现',
    'dashboard.addStock': '添加关注',
    'dashboard.addToWatchlist': '加入关注',
    'dashboard.addedToWatchlist': '已关注',
    'dashboard.errorTitle': '发生错误',
    'dashboard.filters.all': '全部',
    'dashboard.filters.highestConfidence': '最高置信度',
    'dashboard.filters.potentialGrowth': '潜在增长',
    'dashboard.filters.bullish': '看涨',
    'dashboard.filters.bearish': '看跌',
    'dashboard.noStocks': '没有找到符合条件的股票。',
    
    // Add Stock Modal
    'addStock.title': '添加关注',
    'addStock.type': '类型',
    'addStock.typeStock': '股票',
    'addStock.typeEtf': 'ETF基金',
    'addStock.exchange': '交易所',
    'addStock.exchangeSh': '沪市 (sh)',
    'addStock.exchangeSz': '深市 (sz)',
    'addStock.stockCode': '股票代码',
    'addStock.stockCodeHint': '(6位数字)',
    'addStock.stockCodePlaceholder': '例如: 600000',
    'addStock.fullCode': '完整代码:',
    'addStock.errorLength': '请输入6位股票代码',
    'addStock.errorNumeric': '股票代码只能包含数字',
    'addStock.errorNotFound': '未找到该代码，请使用完整代码格式，例如：sz000001 或 sh600519',
    'addStock.errorAuth': '请先登录',
    'addStock.errorDuplicate': '该代码已添加关注',
    'addStock.errorLimitExceeded': '已达到当前会员等级的关注上限。',
    'addStock.errorGeneric': '添加失败',

    // Modal Common
    'modal.deleteTitle': '删除自选',
    'modal.deleteMessage': '确认删除 {symbol}？',
    'modal.deleteConfirm': '删除',
    'modal.deleteCancel': '取消',
    
    // Watchlist Extra
    'watchlist.latestDate': '最新日期',
    'watchlist.turnoverRate': '换手率',
    
    // Strategy
    'strategy.badge': '策略',
    'strategy.configure': '配置参数',
    'strategy.initialCash': '初始资金',
    'strategy.rebalance': '动态平衡',
    'strategy.threshold': '买/卖阈值',
    'strategy.position': '仓位范围',
    'strategy.noConfig': '未配置策略参数',
    'strategy.configureNow': '立即配置',

    // Watchlist
    'watchlist.title': '我的关注列表',
    'watchlist.subtitle': '跟踪您喜爱的股票并监控其表现。',
    'watchlist.searchPlaceholder': '搜索...',
    'watchlist.addStock': '添加关注',
    'watchlist.ticker': '代码 / 公司',
    'watchlist.lastPrice': '最新价格',
    'watchlist.todayChange': '最新涨跌',
    'watchlist.chart': '图表',
    'watchlist.actions': '操作',
    'watchlist.showChart': '查看走势',
    'watchlist.singlePredict': '单次预测',
    'watchlist.tabStock': '股票',
    'watchlist.tabEtf': 'ETF基金',
    'watchlist.emptyTitle': '您的关注列表为空',
    'watchlist.emptySubtitle': '使用上方的搜索栏查找并添加您的第一只股票。',
    'watchlist.noPredictionData': '暂无预测数据',
    'watchlist.overLimitBadge': '已暂停',
    'watchlist.overLimitHint': '超出当前会员等级上限。删除其他关注或升级会员后可继续预测。',
    // Single Prediction
    'singlePrediction.title': 'MTF 预测',
    'singlePrediction.submit': '发起预测',
    'singlePrediction.submitting': '排队中...',
    'singlePrediction.horizonLabel': '预测周期',
    'singlePrediction.contextLabel': '上下文长度',
    'singlePrediction.queueTitle': '队列状态',
    'singlePrediction.jobId': '任务 ID',
    'singlePrediction.reused': '是否复用',
    'singlePrediction.queueDepth': '队列深度',
    'singlePrediction.backend': '执行后端',
    'singlePrediction.stockType': '资产类型',
    'singlePrediction.latestPrice': '最新价格',
    'singlePrediction.mtfVersion': 'MTF 版本',
    'singlePrediction.defaultYears': '历史年数',
    'singlePrediction.bestItem': '最佳分位',
    'singlePrediction.latestDataDate': '最新数据日期',
    'singlePrediction.cutoffDate': '截止日期',
    'singlePrediction.autoToday': '自动取今天',
    'singlePrediction.cacheHit': '是否命中缓存',
    'singlePrediction.resultTitle': '未来价格预测',
    'singlePrediction.predictedChange': '预测涨跌',
    'singlePrediction.emptyTitle': '还没有单次预测结果',
    'singlePrediction.emptySubtitle': '选择预测周期和上下文长度后，即可对当前标的发起一次预测。',
    'singlePrediction.statusIdle': '待发起',
    'singlePrediction.statusQueued': '排队中',
    'singlePrediction.statusRunning': '执行中',
    'singlePrediction.statusSucceeded': '已完成',
    'singlePrediction.statusFailed': '失败',
    'singlePrediction.checking': '查询中...',
    'singlePrediction.checkingTitle': '正在查询已有预测结果',
    'singlePrediction.checkingSubtitle': '弹窗会先查询当前标的的最新单次预测缓存，命中后直接展示。',
    'singlePrediction.cachedReadonly': '已加载已有结果',
    'singlePrediction.yes': '是',
    'singlePrediction.no': '否',
    'singlePrediction.errorGeneric': '发起预测失败',
    'singlePrediction.errorMissingJob': '任务已提交，但未返回任务 ID。',
    'singlePrediction.errorMissingResult': '任务已完成，但结果载荷缺失。',
    'singlePrediction.errorTimeout': '等待预测结果超时。',
    'singlePrediction.errorMissingBest': '当前模型和参数组合没有历史 best，请先训练 MTF 模型。',
    
    // Pricing
    'pricing.title': '解锁高级功能',
    'pricing.subtitle': '通过为认真投资者设计的强大工具和实时洞察来增强您的投资策略。',
    'pricing.features.realTimeData': '实时市场数据',
    'pricing.features.realTimeDataDesc': '通过即时数据更新保持市场领先，无延迟。',
    'pricing.features.advancedCharting': '高级图表工具',
    'pricing.features.advancedChartingDesc': '利用专业级工具进行深入的技术分析。',
    'pricing.features.aiInsights': 'AI驱动的洞察',
    'pricing.features.aiInsightsDesc': '利用我们的AI分析您的投资组合并发现新机会。',
    'pricing.features.unlimitedWatchlists': '无限关注列表',
    'pricing.features.unlimitedWatchlistsDesc': '无限制地跟踪您感兴趣的所有股票。',
    'pricing.features.exclusiveCommunity': '专属社区',
    'pricing.features.exclusiveCommunityDesc': '加入专家交易者的私人社区，分享策略。',
    'pricing.features.adFree': '无广告体验',
    'pricing.features.adFreeDesc': '专注于您的投资，享受干净、无干扰的界面。',
    'pricing.comparePlans': '比较我们的计划',
    'pricing.feature': '功能',
    'pricing.free': '免费',
    'pricing.vip': 'VIP',
    'pricing.dataRefreshRate': '数据刷新率',
    'pricing.standard': '标准',
    'pricing.realTime': '实时',
    'pricing.numberOfWatchlists': '关注列表数量',
    'pricing.unlimited': '无限制',
    'pricing.advancedAnalytics': '高级分析',
    'pricing.aiPortfolioInsights': 'AI投资组合洞察',
    'pricing.exclusiveCommunityAccess': '专属社区访问',
    'pricing.prioritySupport': '优先客户支持',
    'pricing.adFreeExperience': '无广告体验',
    'pricing.vipMembership': 'VIP会员',
    'pricing.monthlyPrice': '¥128',
    'pricing.perMonth': '/ 月',
    'pricing.billingInfo': '按月计费，随时取消。',
    'pricing.allVipFeatures': '包含所有VIP功能',
    'pricing.priorityCustomerSupport': '优先客户支持',
    'pricing.earlyAccess': '抢先体验测试版功能',
    'pricing.upgradeToVip': '升级到VIP',
    
    // Login
    'login.title': '您的投资组合，完美无缺。',
    'login.subtitle': '通过AI驱动的预测和无与伦比的洞察跟踪您的股票。今天就做出更明智的投资决策。',
    'login.welcomeBack': '欢迎回来',
    'login.createAccount': '创建账户',
    'login.fullName': '姓名',
    'login.fullNamePlaceholder': '请输入您的姓名',
    'login.emailAddress': '邮箱地址',
    'login.emailPlaceholder': '请输入您的邮箱',
    'login.password': '密码',
    'login.passwordPlaceholder': '请输入您的密码',
    'login.activationCode': '会员邀请码',
    'login.activationCodePlaceholder': '请输入会员邀请码',
    'login.signIn': '登录',
    'login.register': '注册',
    'login.forgotPassword': '忘记密码？',
    'login.loginTab': '登录',
    'login.registerTab': '注册',
    'login.or': '或',
    'login.continueWithGoogle': '使用Google继续',
    'login.loginButton': '登录',
    'login.registerButton': '注册',
    'login.rememberPassword': '保存密码',
    'login.loggingIn': '登录中...',
    'login.registering': '注册中...',
    'login.captchaReady': '安全验证已就绪',
    'login.captchaLoading': '正在加载安全验证...',
    'login.captchaFailed': '安全验证失败，请重试。',
    'login.captchaLoadFailed': '安全验证加载失败。',
    'login.captchaUnavailable': '安全验证暂不可用。',

    // Auth
    'auth.sessionExpired': '会话已过期',
    'auth.redirectingLogin': '请先登录，正在跳转...',
    'auth.checking': '正在验证登录状态...',

    // Admin
    'admin.noAccessTitle': '无管理员权限',
    'admin.noAccessDesc': '当前账号不能访问管理员页面。',

    // UZI / Research Skill
    'watchlist.uziManage': 'UZI 管理',
    'uzi.title': '研报Skill',
    'uzi.subtitle': '统一管理 UZI 研报的查询、生成与删除。',
    'uzi.invalidTicker': '请输入有效的股票代码，例如 601766.SH',
    'uzi.ticker': '股票代码',
    'uzi.tickerPlaceholder': '例如 601766.SH 或 sh601766',
    'uzi.generateDepth': '生成深度',
    'uzi.query': '查询',
    'uzi.refresh': '刷新',
    'uzi.generating': '生成中...',
    'uzi.generate': '生成',
    'uzi.reportList': '报告列表',
    'uzi.reportCount': '份报告',
    'uzi.emptyHint': '当前还没有生成过 UZI 报告',
    'uzi.empty': '暂无 UZI 报告，点击上方生成即可创建。',
    'uzi.updatedAt': '更新时间',
    'uzi.open': '查看',
    'uzi.deleting': '删除中...',
    'uzi.delete': '删除',
    'uzi.searchPlaceholder': '搜索代码或目录',
    
    // Language
    'language.switch': '语言',
    'language.english': 'English',
    'language.chinese': '中文',

    // Sidebar
    'sidebar.hello': '你好',
    'sidebar.loading': '加载中...',
    'sidebar.title': 'MeetLife AI',
    'sidebar.member.standard': '普通会员',

    // MTF Agent
    'mtfAgent.title': 'MTF 智能体',
    'mtfAgent.open': '打开 MTF 智能体',
    'mtfAgent.close': '关闭 MTF 智能体',
    'mtfAgent.resize': '调整 MTF 智能体抽屉宽度',
    'mtfAgent.dragResize': '拖动调整宽度',
    'mtfAgent.memory': '长期记忆',
    'mtfAgent.reset': '重置会话',
    'mtfAgent.emptyResponse': 'MTF 智能体暂时没有返回内容，请稍后重试。',
    'mtfAgent.configRequired': '请先在设置中配置 AI 模型。',
    'mtfAgent.runtimeUnavailable': 'MTF Agent runtime 尚未连接。',
    'mtfAgent.unavailable': 'MTF Agent 暂不可用',
    'mtfAgent.resetSuccess': '已重置为新的 MTF Agent 会话。',
    'mtfAgent.resetFailed': '重置会话失败',
    'mtfAgent.memoryLoadFailed': '读取长期记忆失败',
    'mtfAgent.memoryClearFailed': '清空长期记忆失败',
    'mtfAgent.waitRuntime': '等待 runtime 连接',
    'mtfAgent.memoryTitle': '长期偏好',
    'mtfAgent.loadingMemory': '正在读取...',
    'mtfAgent.emptyMemory': '暂无长期偏好',
    'mtfAgent.connecting': '正在连接 MTF Agent...',
    'mtfAgent.emptyHint': '可以询问自选股、预测结果、UZI 研报和组合相关问题。',
    'mtfAgent.thinking': '正在思考...',
    'mtfAgent.resetConfirmText': '重置会创建新的长期会话，当前窗口消息会清空。',
    'mtfAgent.resetting': '重置中',
    'mtfAgent.confirmReset': '确认重置',
    'mtfAgent.goSettings': '去设置',
    'mtfAgent.placeholder': '询问自选股、预测、研报或组合...',

    // Landing Page
    'landing.startForFree': '免费开始',
    'landing.viewDemo': '查看演示',
    'landing.features.aiPredictions': 'AI 预测',
    'landing.features.aiPredictionsDesc': '先进的机器学习算法预测股票走势。',
    'landing.features.realTimeAnalysis': '实时分析',
    'landing.features.realTimeAnalysisDesc': '实时市场数据分析，助您领先一步。',
    'landing.features.securePortfolio': '安全投资组合',
    'landing.features.securePortfolioDesc': '银行级安全保障，保护您的投资数据。',
    'landing.footer.rights': '© 2024 FinTrack. 保留所有权利。',

    // Stock Prediction Card
    'prediction.model': '模型',
    'prediction.context': '上下文',
    'prediction.horizon': '周期',
    'prediction.days': '天',
    'prediction.maxDev': '最大偏差',
    'prediction.score': '最佳得分',
    'prediction.actual': '实际',
    'prediction.pred': '预测',
    'prediction.actChg': '实际涨跌',
    'prediction.predChg': '预测涨跌',
    'prediction.watchlistCount': '关注',
    'prediction.hideMetrics': '收起指标',
    'prediction.showMetrics': '展开指标',
    'prediction.awaitingAI': '等待 AI 预测...',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  // 从localStorage加载语言设置
  useEffect(() => {
    const savedLanguage = localStorage.getItem('fintrack-language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // 设置语言并保存到localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('fintrack-language', lang);
  };

  // 翻译函数
  const t = (key: string, fallback?: string): string => {
    return translations[language][key] || fallback || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook for using language context
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
